apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nakama.fullname" . }}-database
  labels:
    component: database
    {{- include "nakama.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: database
      {{- include "nakama.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: database
        {{- include "nakama.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - start-single-node
        - --insecure
        - --store=attrs=ssd,path=/var/lib/cockroach/
        image: {{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}
        imagePullPolicy: {{ .Values.database.image.pullPolicy }}
        name: db
        ports:
        - containerPort: {{ .Values.database.port }}
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/cockroach
          name: data
      restartPolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "nakama.fullname" . }}
      {{- with .Values.nodeName }}
      nodeName: {{ . }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
