apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nakama.fullname" . }}-database
  labels:
    component: database
    {{- include "nakama.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: database
      {{- include "nakama.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: database
        {{- include "nakama.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - start
        - --insecure
        - --store=attrs=ssd,path=/var/lib/cockroach/
        image: cockroachdb/cockroach:v19.2.5
        imagePullPolicy: ""
        name: cockroachdb
        ports:
        - containerPort: {{ .Values.database.port }}
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/cockroach
          name: data
      restartPolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "nakama.fullname" . }}
