apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nakama.fullname" . }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.size }}
status: {}
