apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nakama.fullname" . }}-node
  labels:
    component: node
    {{- include "nakama.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: node
      {{- include "nakama.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        component: node
        {{- include "nakama.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-database
          image: busybox
          args:
            - /bin/sh
            - -c
            - >
              set -x;
              while [ $(curl -sw '%{http_code}' "{{ include "nakama.fullname" . }}-database:{{ .Values.database.port }}" -o /dev/null) -ne 200 ]; do
                sleep 15;
              done;
              sleep 15;
      containers:
      - name: nakama
        command:
        - /bin/sh
        - -ecx
        - |
          /nakama/nakama migrate up --database.address root@{{ include "nakama.fullname" . }}-database:{{ .Values.database.port }} &&
           exec /nakama/nakama --database.address root@{{ include "nakama.fullname" . }}-database:{{ .Values.database.port }} --config /nk-config/nakama-config.yml
        image: {{ required "You have to give your custom Nakama container image" .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}
        {{- with .Values.extraEnvs }}
        env:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          {{- with .Values.extraConfigMaps }}
          - name: config-volume-extra
            mountPath: /nk-config/nakama-extra-config.yml
            subPath: nakama-extra-config.yml
          {{- end }}
          - name: config-volume
            mountPath: /nk-config/nakama-config.yml
            subPath: nakama-config.yml
        livenessProbe:
          httpGet:
            path: .
            port: {{ .Values.socket.port }}
            scheme: HTTP
          initialDelaySeconds: 30
        ports:
        - containerPort: {{ .Values.grpc.port }}
        - containerPort: {{ .Values.socket.port }}
        - containerPort: {{ .Values.console.port }}
        - containerPort: {{ .Values.console.grpc }}
        - containerPort: {{ .Values.monitoring.metrics.prometheusPort }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- with .Values.extraConfigMaps }}
        - name: config-volume-extra
          configMap:
            name: {{ include "nakama.fullname" $ }}-extra-cm
        {{- end }}
        - name: config-volume
          configMap:
            name: {{ include "nakama.fullname" . }}

      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeName }}
      nodeName: {{ . }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
