{{- if eq .Values.database.type "postgres" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nakama.fullname" . }}-database
  labels:
    component: database
    {{- include "nakama.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: database
      {{- include "nakama.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: database
        {{- include "nakama.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - command:
        - /bin/sh
        - -ecx
        - |
          docker-entrypoint.sh -c 'shared_preload_libraries=pg_stat_statements' -c 'pg_stat_statements.track=all'
        image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
        imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
        name: db
        env:
          - name: POSTGRES_DB
            value: nakama
          - name: POSTGRES_PASSWORD
            value: localdb
        ports:
        - containerPort: {{ .Values.database.port }}
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data
      restartPolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "nakama.fullname" . }}
      {{- with .Values.nodeName }}
      nodeName: {{ . }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
